# Generated by Django 4.1.2 on 2022-10-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='Description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='note',
            name='Title',
            field=models.CharField(max_length=15, verbose_name='Title'),
        ),
    ]
